//
//  MainMapModel.swift
//
//  Created by Tarsha De Souza on 08/07/2020.
//  Copyright (c) 2020 TarshaDeSouza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainMap {
	
	enum Model {
		
		struct Request {
			
		}
		
		struct Response {
			let meeps: MeepViewObject
		}
		
		struct ViewModel {
			let meeps: MeepViewObject
		}
	}
}
