//
//  MainMapRouter.swift
//
//  Created by Tarsha De Souza on 08/07/2020.
//  Copyright (c) 2020 TarshaDeSouza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMapRouterProtocol: NSObjectProtocol, MainMapRoutingLogicProtocol, MainMapDataPassingProtocol {
}

@objc protocol MainMapRoutingLogicProtocol {
    func routeToSomewhere(_ segue: UIStoryboardSegue?)
}

protocol MainMapDataPassingProtocol {
  var dataStore: MainMapDataStoreProtocol? { get }
}

class MainMapRouter: NSObject, MainMapRouterProtocol {
    
  weak var view: MainMapViewProtocol?
  var dataStore: MainMapDataStoreProtocol?
  
    init(view: MainMapViewProtocol,
         dataStore: MainMapDataStoreProtocol?) {
        self.view = view
        self.dataStore = dataStore
    }

    func routeToSomewhere(_ segue: UIStoryboardSegue?) {
//        if let segue = segue, let somewhereViewController = segue.destination as? SomewhereViewController {
//            passDataToNextScene(destination: somewhereViewController)
//        } else if let somewhereViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SomewhereViewControllerViewController") as? SomewhereViewControllerController {
//            passDataToNextScene(destination: somewhereViewController)
//            navigate(to: somewhereViewController)
//        }
    }

    private func navigate(to destination: UIViewController) {
        if let viewController = view as? UIViewController {
            viewController.present(destination, animated: true, completion: nil)
        }
    }

    private func passDataToNextScene(destination: UIViewController?) {
//        if let view = destination as? SomewhereViewController,
//            var somewhereDataStore = view.router?.dataStore,
//            let value = dataStore?.value {
//            somewhereDataStore.value = value
//        }
    }
}
