//
//  MainMapRouter.swift
//
//  Created by Tarsha De Souza on 08/07/2020.
//  Copyright (c) 2020 TarshaDeSouza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMapRouterProtocol: NSObjectProtocol, MainMapRoutingLogicProtocol, MainMapDataPassingProtocol {
}

@objc protocol MainMapRoutingLogicProtocol {
}

protocol MainMapDataPassingProtocol {
	var dataStore: MainMapDataStoreProtocol? { get }
}

class MainMapRouter: NSObject, MainMapRouterProtocol {
	
	weak var view: MainMapViewProtocol?
	var dataStore: MainMapDataStoreProtocol?
	
	init(view: MainMapViewProtocol,
		 dataStore: MainMapDataStoreProtocol?) {
		self.view = view
		self.dataStore = dataStore
	}
}
