//
//  MainMapMocks.swift
//
//  Created by Tarsha De Souza on 08/07/2020.
//  Copyright (c) 2020 TarshaDeSouza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import <MODULE_NAME>

class MainMapPresenterMock: MainMapPresenterProtocol {
	
		var presentResponseCalled = false
		var presentErrorCalled = false
		
		func presentSomething(response: MainMap.Model.Response) {
			presentResponseCalled = true
		}
		
		func present(error: Error) {
			presentErrorCalled = true
		}
}
