//
//  MainMapTests.swift
//
//  Created by Tarsha De Souza on 08/07/2020.
//  Copyright (c) 2020 TarshaDeSouza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import <MODULE_NAME>

class MainMapInteractorTests: XCTestCase {
    
	private var presenter: MainMapPresenterMock!
	private var interactor: MainMapBusinessLogicProtocol!

	override func setUp() {
        super.setUp()
		presenter = MainMapPresenterMock()
		interactor = MainMapInteractor(presenter: presenter)
	}
	
	override func tearDown() {
		presenter = nil
		interactor = nil
        super.tearDown()
	}

	func testDoSomethingSuccess() {
		let request = MainMap.Model.Request()
		_ = interactor.doSomething(request: request)
		XCTAssertTrue(presenter.presentResponseCalled, "Interactor did not call presenter when after successful call")
	}

}
